# Generated by Django 2.0.4 on 2018-09-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default='loc_20189633330de735f5', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(default='sta_2018963333aa1233c1', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Location')),
            ],
        ),
    ]
